repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      # standard end of line/end of file cleanup
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # ensure syntaxes are valid
      - id: check-toml
      - id: check-yaml
      - id: check-json
      # catch git merge/rebase problems
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        types_or: [python]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==21.11b1]
        types_or: [python]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        types_or: [python]
  - repo: https://github.com/PyCQA/pylint
    rev: v2.13.7
    hooks:
      - id: pylint
        args: [--exit-zero]
        types_or: [python]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [--exit-zero]
        types_or: [python]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        types_or: [ts]
